rbac:
  create: true
controller:
  replicaCount: 2
  config:
    use-proxy-protocol: "true"
  service:
    spec:
      externalTrafficPolicy: Local
    annotations:
      external-dns.alpha.kubernetes.io/hostname: <DOMAIN FOR HOSTING JUPYTERHUB> 
  publishService:
    enabled: true